#!/bin/bash

#docker-compose stop apiweb

#dotnet build

#rm -R dist/

#dotnet publish --configuration Release --output dist

#docker-compose down apiweb

#docker rmi -f systeme_financier_personnel_apiweb:latest

#docker-compose build apiweb
#sleep 1000
#docker-compose up -d

docker-compose restart apiweb