#!/bin/bash
# git checkout --  mssql_bd/
# git checkout --  dist/
git checkout --  bin/
git checkout --  obj/

#git checkout --  mssql_bd/
git checkout -- mssql_bd/.system/
git checkout -- mssql_bd/log/
git checkout -- mssql_bd/secrets
